services:
  php84:
    build:
      context: .
      dockerfile: docker/php84/Dockerfile
    container_name: php-testbench.craftzing.php84
    restart: unless-stopped
    tty: true
    working_dir: /code
    volumes:
      - ./:/code:delegated
