name: Code style
on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest
      - run: composer phpstan

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run PHP CS fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes
      - name: Commit CS fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style violations
