---
name: Quality assurance
on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        php: [8.3, 8.4]
        dependency-version: [prefer-lowest, prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Run PHPStan analysis
        run: vendor/bin/phpstan analyse --memory-limit=-1
        if: ${{ matrix.php == '8.3' }}