name: Static analysis
on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest
      - run: composer phpstan

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run PHP CS fixer
        uses: ./.github/actions/php-cs-fixer.yml
        with:
          args: --config=.php-cs-fixer.dist.php --allow-risky=yes
      - name: Commit CS fixes
        uses: craftzing/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
        with:
          commit_message: Fix code style violations
