name: static-analysis
on:
  pull_request:
  push:
    branches: ['main']

jobs:
  mago:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # https://github.com/shivammathur/setup-php/releases/tag/2.37.1
        with:
          php-version: 8.5
          extensions: -pdo_mysql, -mysqli
      - run: composer update --prefer-stable --prefer-dist --no-interaction
      - run: composer mago:lint
        id: lint
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: composer mago:format -- --dry-run
        id: format
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Report issues detected by Mago'
        if: steps.lint.outcome == 'failure' || steps.format.outcome == 'failure'
        env:
          LINT_OUTCOME: ${{ steps.lint.outcome }}
          FORMAT_OUTCOME: ${{ steps.format.outcome }}
        run: |
          if [ "$LINT_OUTCOME" == "failure" ]; then
            echo "::error title=Mago linter detected issues::"
          fi
          
          if [ "$FORMAT_OUTCOME" == "failure" ]; then
            echo "::error title=Mago formatter detected issues::"
          fi
          
          exit 1
