name: test
on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        php: [8.4, 8.5]
        dependency-version: [prefer-lowest, prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # https://github.com/shivammathur/setup-php/releases/tag/2.37.1
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - run: composer coverage:summary
